### ISSUE TITLE
Editing Units

### ISSUE THREAD

**Issue by nweissoertel** [CheesiestMaster/armcobot#3]
- admin command that allows modifying a unit, with a distinction in how it handles inactive versus active units
- what exactly is editable is TBD

**Comment by Whitehowle** [comment]
@CheesiestMaster 

I have a concept for Players Editing the Unit Name and Unit Type for PROPOSED units only. Are there any other things you'd like players to be able to edit?


For Admins

They can Edit any unit type, however I would think we put a hard limit to prevent them from changing a unit status to Active if there already is an active unit for that player.
